### PR TITLE
Configure nginx ingress with host IP

### PR DESCRIPTION
**Pull request by panlinux**
If possible, use the host IP when setting the nginx ingress "public" IP.

Fixes issue #824

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you for this PR @panlinux. Looks great!

As the 1.19 release is scheduled for next week I am going to hold off this PR for a bit.

I appreciate your patience. Cheers.

**Comment by panlinux** [comment]
Oh, I thought the edge channel would have something like a daily build, exactly to test changes like these, but looks like it's behind.

**Comment by ktsakalozos** [comment]
> to test changes like these

You can get the built snap as an artifact of the github workflow/test.

**Comment by panlinux** [comment]
ok, built the arm64 snap with this change, and the other one suggested in https://github.com/ubuntu/microk8s/issues/824#issuecomment-688491339, but still need to test them.
This one here I did a quick deploy and saw the public address being the one from the host. What I would like to do next is change the ip of the host, and see what happens after a reboot. I suspect it will break things, which is where the second suggested change should be better, but I have to check.

**Comment by ktsakalozos** [comment]
We also need to figure out how we will going to handle the change of the default IP (eg a laptop changing networks).

**Comment by panlinux** [comment]
The pod would have to be restarted I guess.
Stupid question: would this work?
```
--publish-status-address=0.0.0.0
```

**Comment by patsevanton** [comment]
Can i help for resolve this PR?

**Comment by amirhs712** [comment]
Hey, can we resolve this PR, please?

**Comment by typoworx-de** [comment]
IP address should be configureable and fallback should be Host-IP or 127.0.0.1.

**Comment by jniclas** [comment]
Hey, I had the problem too now by trying to use ingress with external-dns, where it picket the 127.0.01. Is it posibble to still integrate that?

**Pull request closed without merging**
