### PR TITLE
Use https url to perform connectivity check

### LINKED ISSUE #3978: Internet connectivity check fails if ICMP traffic is restricted
#### Summary

When trying to install on macOS I get a failure to connect to the internet, the check is done via a ping (ICMP) traffic which isn't allowed on my corp network. However http/https (which are the connections actually required) are fine. I can't see any other use of ping other than a test.

#### What Should Happen Instead?

The internet check should check for http(s) connectivity instead of using ping.

#### Reproduction Steps

1. be on network that disallows ICMP traffic
2. microk8s install

#### Introspection Report

N/A

#### Can you suggest a fix?

https://github.com/canonical/microk8s/blob/master/installer/vm_providers/_base_provider.py#L131

`curl --fail --head https://snapcraft.io` instead perhaps?

#### Are you interested in contributing with a fix?

Yes

### PR DESCRIPTION
**Pull request by smithyuk**
#### Summary

Change internet connectivity check to use HTTPS, previous check was for ICMP which may not be possible and doesn't confirm whether further steps will work correctly

Closes #3978 

#### Changes

Change internet connectivity check to use HTTPS

#### Testing

Tested code in isolation

#### Checklist

* [x] Read the [contributions](https://github.com/canonical/microk8s/blob/master/CONTRIBUTING.md) page.
* [x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
* [x] The introduced changes are covered by unit and/or integration tests.

### CODE REVIEW

**Comment by smithyuk** [comment]
Re-signed CLA (using email as launchpad id this time) and joined group

**Comment by bschimke95** [comment]
Hi @smithyuk 
Seems like there is still an issue with the CLA.
```
- smithyuk1@live.co.uk ✕ (has not signed the CLA)
```
Could you please check again?

**Comment by smithyuk** [comment]
> Hi @smithyuk Seems like there is still an issue with the CLA.
> 
> ```
> - smithyuk1@live.co.uk ✕ (has not signed the CLA)
> ```
> 
> Could you please check again?

Re-signed, I think this is looking up based on email and not whatever I set my GitHub username to in the CLA signing. So I signed with the same email that my commit was as. Cheers

**Review by neoaggelos — APPROVED** [review]
LGTM!

**Pull request merged**
