### PR TITLE
fix grep search for kubelet token

### LINKED ISSUE #3329: microk8s master node status NotReady when refresh-certs is executed
#### Summary

When running the command `sudo microk8s refresh-certs` on a master node, it gives me sed error and caused the master node to go to NotReady status

```
~$ sudo microk8s refresh-certs
Taking a backup of the current certificates under /var/snap/microk8s/2530/var/log/ca-backup/
Creating new certificates
Signature ok
subject=/C=GB/ST=Canonical/L=Canonical/O=Canonical/OU=Canonical/CN=127.0.0.1
Getting CA Private Key
Signature ok
subject=/CN=front-proxy-client
Getting CA Private Key
1
Creating new kubeconfig file
/snap/microk8s/2530/bin/sed: -e expression #1, char 71: unterminated `s' command
Stopped.
Started.

The CA certificates have been replaced. Kubernetes will restart the pods of your workloads.
Any worker nodes you may have in your cluster need to be removed and re-joined to become aware of the new CA.
```

The error was due to having "kubelet-0" string found twice in known_hosts.csv as a result of the said command below
```
kubelet_token=`grep kubelet-0 ${SNAP_DATA}/credentials/known_tokens.csv | cut -d, -f1`
```

#### What Should Happen Instead?

Master node should be able to be on Ready state while successfully refreshing the certificates

#### Reproduction Steps

1. `sudo microk8s refresh-certs`

#### Can you suggest a fix?

Suggested fix is to make the grep command for kubelet-token to be more specific

#### Are you interested in contributing with a fix?

Yes.

### PR DESCRIPTION
**Pull request by ortegarenzy**
#### Summary

Enhanced the grep search for kubelet token by specifying additional criteria for the search string

Closes #3329 

#### Changes

Added additional criteria on search string for searching kubelet-0

### CODE REVIEW

**Review by neoaggelos — APPROVED** [review]
LGTM @ortegarenzy!

Do you mind taking a minute to submit the CLA form? And then we are good to merge this. Thanks!

**Comment by ortegarenzy** [comment]
@neoaggelos Just submitted the CLA form. Can you verify ?

**Comment by ktsakalozos** [comment]
Hi @ortegarenzy, it seems that you PR is failing the CLA check because your initial commit was done using the `renzy.ortega@jobandesther.com` email. Could you please address that? You can either sign the CLA using that email too or quash all your commits under a single one from the ortegarenzy user on github.

**Comment by ortegarenzy** [comment]
@ktsakalozos Hi, I have squash the commits now and it should use the ortegarenzy user on github as the commit author for the single commit on the PR.

**Comment by ktsakalozos** [comment]
Thank you for this fix @ortegarenzy

**Pull request merged**
