### PR TITLE
[backport/1.25] Increase daemon-containerd timeout and order daemon-kubelite after it

### PR DESCRIPTION
**Pull request by mfoliveira**
This is a cherry-pick of PR #3685 to release branch 1.25.

Summary of test steps (see PR for details):

Before:
```
$ sudo snap install microk8s --classic --channel=1.25/edge
$ snap info microk8s | grep 1.25/edge:
  1.25/edge:             v1.25.6         2023-02-09 (4677) 175MB classic
...
$ systemctl show snap.microk8s.daemon-containerd.service | grep NRestarts
NRestarts=3
$ systemctl show snap.microk8s.daemon-kubelite.service | grep NRestarts
NRestarts=12
```

After:
```
$ git log --oneline -2
b0a417c039c8 (daemon-containerd-timeout-1.25) Increase daemon-containerd timeout and order daemon-kubelite after it (#3685)
a15a5691c159 (origin/1.25) Update containerd to 1.6.15 (#3745)

$ sudo snap install ./microk8s_v1.25.6_amd64.snap --classic --dangerous
...
$ systemctl show snap.microk8s.daemon-containerd.service | grep NRestarts
NRestarts=0
$ systemctl show snap.microk8s.daemon-kubelite.service | grep NRestarts
NRestarts=0
```

#### Checklist

* [ ] Read the [contributions](https://github.com/canonical/microk8s/blob/master/CONTRIBUTING.md) page.
* [ ] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
* [ ] The introduced changes are covered by unit and/or integration tests.

### CODE REVIEW

**Comment by mfoliveira** [comment]
The error in check `Build and test MicroK8s snap / Test core addons (pull_request)` is unrelated to this change (python attribute error), and is also observed in other open/current PRs.

```
=================================== FAILURES ===================================
__________________________ TestAddons.test_help_text ___________________________

self = <test-addons.TestAddons object at 0x7f79d2999220>

    def test_help_text(self):
        status = yaml.safe_load(
>           sh.microk8s.status("--wait-ready", "--timeout=600", format="yaml").stdout
        )
E       AttributeError: 'str' object has no attribute 'stdout'

test-addons.py:52: AttributeError
```

**Comment by neoaggelos** [comment]
@mfoliveira can you please rebase this PR as well? Thanks!

**Comment by neoaggelos** [comment]
Rebased, will merge after CI is green

**Comment by mfoliveira** [comment]
@neoaggelos thanks! I just got back from time off/holidays.

**Pull request merged**
