### PR TITLE
Update community tests to point to a folder

### PR DESCRIPTION
**Pull request by berkayoz**
#### Summary

This is a follow up PR for [microk8s-community-addons#120](https://github.com/canonical/microk8s-community-addons/pull/120).

#### Changes

Updated tests so pytest targets a folder instead of the `test-addons.py`.

#### Checklist

* [x] Read the [contributions](https://github.com/canonical/microk8s/blob/master/CONTRIBUTING.md) page.
* [x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
* [x] The introduced changes are covered by unit and/or integration tests.

### CODE REVIEW

**Review by neoaggelos — APPROVED** [review]
Should we do the same for core addons as well while we're at it?

**Comment by berkayoz** [comment]
Thank's for the review. Agreed, we can convert core addons to the same structure. However, the folder detection method does not work for `test-addons.py`, since it uses a `-` instead of a `_`.  The other option is doing `./tests/test*.py` which is less preferable. We'd need to merge the PR for addons first to get the checks to pass.

**Comment by neoaggelos** [comment]
No, let's skip the wildcards, my vote is to rename to `test_addons` and adjust accordingly.

**Comment by berkayoz** [comment]
Let's continue for the core addons on a separate PR as we need to merge this at the same time with the community addons to not break new PRs. I also agree we can start by changing to `test_addons`.

**Pull request merged**
